package com.example.bean.exampleBean;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userId
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userName
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.passWord
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.isUse
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    private Integer isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.creatDate
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    private Date creatDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userId
     *
     * @return the value of userinfo.userId
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userId
     *
     * @param userId the value for userinfo.userId
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userName
     *
     * @return the value of userinfo.userName
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userName
     *
     * @param userName the value for userinfo.userName
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.passWord
     *
     * @return the value of userinfo.passWord
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.passWord
     *
     * @param passWord the value for userinfo.passWord
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.isUse
     *
     * @return the value of userinfo.isUse
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    public Integer getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.isUse
     *
     * @param isUse the value for userinfo.isUse
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    public void setIsUse(Integer isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.creatDate
     *
     * @return the value of userinfo.creatDate
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    public Date getCreatDate() {
        return creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.creatDate
     *
     * @param creatDate the value for userinfo.creatDate
     *
     * @mbggenerated Tue Aug 27 15:12:51 CST 2019
     */
    public void setCreatDate(Date creatDate) {
        this.creatDate = creatDate;
    }
}